### ISSUE TITLE
ReferenceError: AWater is not defined

### ISSUE THREAD

**Issue by Atlinx** [Dante83/a-water#3]
I'm trying to use this library in Typescript by importing it, however I'm getting the following error:

```
ReferenceError: AWater is not defined
```

**Comment by Dante83** [comment]
Never tried it in Typescript, but I wouldn't be surprised. You'll notice the script code isn't actually a JS module, so importing it like that is probably not going to work. It's meant to be configured as a custom A-Frame HTML DOM element. I did a more traditional style namespace effort here, internally,

https://github.com/Dante83/a-water/blob/master/src/js/AWater.js

So if you have access to the global namespace you can probably just reference A-Water after it's set up like a regular object with nested internal objects of different types, modifying them as you like in your own run loop - though it isn't designed for that. Also, be warned, that structure isn't guaranteed to stay the same with time. I have an update in the wings, but I've been a bit lazy about getting it wrapped up and off the ground after a new job started up which is zapping up all my attention while I get up to speed. Sorry about that, not sure if it helps.

**Comment by Atlinx** [comment]
Yeah I ended up making some corrections to the JS file and I managed to get it to a somewhat working state. However my target platform is mobile devices so I ultimately had to abandon it due to performance issues.

Your library is nonetheless very impressive and would be useful for a desktop AFrame experience. 😄

**Comment by Dante83** [comment]
It's very true, it's a definite GPU hog, to be sure. I was hoping the latest update would make things better, but it seems my efforts were in vain and any performance gains I acquired were lost to graphical improvements - at best.
